/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'transformation' : IDL.Text,
  'review' : IDL.Text,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllTestimonialsByRating' : IDL.Func(
      [],
      [IDL.Vec(Testimonial)],
      ['query'],
    ),
  'getTestimonial' : IDL.Func([IDL.Nat], [Testimonial], ['query']),
  'init' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'transformation' : IDL.Text,
    'review' : IDL.Text,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllTestimonialsByRating' : IDL.Func(
        [],
        [IDL.Vec(Testimonial)],
        ['query'],
      ),
    'getTestimonial' : IDL.Func([IDL.Nat], [Testimonial], ['query']),
    'init' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };